language: python
cache:
  pip: true
  directories:
  - eggs
  - downloads
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
python:
  - 2.7
matrix:
  fast_finish: true
before_install:
  - pip install zc.buildout
  - wget "http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
install:
  - buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/code-analysis
  - bin/test --all
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - sneridagh@gmail.com
